export const INDEX_SWIPER = 'INDEX_SWIPER'
export const ACCOUNT_TITLE = 'ACCOUNT_TITLE'
export const SOURCE_URL = 'SOURCE_URL'
export const USER_STATE = 'USER_STATE'
export const USER_INFO = 'USER_INFO'
